import type {
  KpiMetric,
  RevenueChartData,
  Tutor,
  Student,
  EscrowTransaction,
  PayoutRequest,
  Dispute,
} from "./types";

// ===== Mock KPI Data =====
export const mockKpiMetrics: KpiMetric[] = [
  {
    id: "gmv",
    title: "Tổng GMV",
    value: "1,245,000,000đ",
    change: "+15.2%",
    changeType: "increase",
    icon: "TrendingUp",
    color: "blue",
  },
  {
    id: "revenue",
    title: "Doanh thu Phí nền tảng",
    value: "149,400,000đ",
    change: "+12.8%",
    changeType: "increase",
    icon: "Wallet",
    color: "green",
  },
  {
    id: "new_users",
    title: "Người dùng mới",
    value: "1,284",
    change: "+248 HS / +36 Gia sư",
    changeType: "increase",
    icon: "Users",
    color: "purple",
  },
  {
    id: "bookings",
    title: "Lớp học đang diễn ra",
    value: "387",
    change: "+8.1%",
    changeType: "increase",
    icon: "CalendarCheck",
    color: "orange",
  },
];

// ===== Mock Revenue Chart Data =====
export const mockRevenueData: RevenueChartData[] = [
  { month: "T1", revenue: 820000000, bookings: 240 },
  { month: "T2", revenue: 940000000, bookings: 275 },
  { month: "T3", revenue: 1010000000, bookings: 301 },
  { month: "T4", revenue: 880000000, bookings: 262 },
  { month: "T5", revenue: 1120000000, bookings: 325 },
  { month: "T6", revenue: 1050000000, bookings: 310 },
  { month: "T7", revenue: 1180000000, bookings: 341 },
  { month: "T8", revenue: 1245000000, bookings: 387 },
];

// ===== Mock Tutors =====
export const mockTutors: Tutor[] = [
  {
    id: "t1",
    name: "Nguyễn Thị Lan Anh",
    email: "lananh.nguyen@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lananh",
    phone: "0901234567",
    subjects: ["Toán", "Vật lý"],
    status: "under_review",
    reputationScore: 0,
    subscriptionPlan: "free",
    submittedAt: "2026-05-05T08:30:00Z",
    totalEarnings: 0,
    totalSessions: 0,
  },
  {
    id: "t2",
    name: "Trần Minh Tuấn",
    email: "minhtuan.tran@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=minhtuan",
    phone: "0912345678",
    subjects: ["IELTS", "Tiếng Anh"],
    status: "under_review",
    reputationScore: 0,
    subscriptionPlan: "free",
    submittedAt: "2026-05-04T14:00:00Z",
    totalEarnings: 0,
    totalSessions: 0,
  },
  {
    id: "t3",
    name: "Phạm Thị Mai",
    email: "mai.pham@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maipham",
    phone: "0923456789",
    subjects: ["Hóa học", "Sinh học"],
    status: "under_review",
    reputationScore: 0,
    subscriptionPlan: "free",
    submittedAt: "2026-05-04T09:15:00Z",
    totalEarnings: 0,
    totalSessions: 0,
  },
  {
    id: "t4",
    name: "Lê Văn Khoa",
    email: "vankhoa.le@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=vankhoa",
    phone: "0934567890",
    subjects: ["Lập trình", "Toán rời rạc"],
    status: "approved",
    reputationScore: 85,
    subscriptionPlan: "standard",
    submittedAt: "2026-04-20T10:00:00Z",
    approvedAt: "2026-04-22T11:00:00Z",
    totalEarnings: 12500000,
    totalSessions: 48,
  },
  {
    id: "t5",
    name: "Võ Thị Hương",
    email: "thihuong.vo@email.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=thihuong",
    phone: "0945678901",
    subjects: ["Văn học", "Ngữ văn"],
    status: "rejected",
    reputationScore: 0,
    subscriptionPlan: "free",
    submittedAt: "2026-05-01T16:00:00Z",
    rejectedAt: "2026-05-03T10:00:00Z",
    rejectionReason: "Bằng cấp không rõ ràng, video giới thiệu quá ngắn (< 30s).",
    totalEarnings: 0,
    totalSessions: 0,
  },
];

// ===== Mock Students =====
export const mockStudents: Student[] = [
  {
    id: "s1",
    name: "Đinh Văn Bình",
    email: "vanbinhh@gmail.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=vanbinh",
    phone: "0901122334",
    grade: "Lớp 12",
    status: "active",
    totalSpent: 4500000,
    totalClasses: 24,
    registeredAt: "2026-03-10T00:00:00Z",
  },
  {
    id: "s2",
    name: "Nguyễn Khánh Linh",
    email: "khanhlinhngoc@gmail.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=khanhlinh",
    phone: "0912233445",
    grade: "Đại học",
    status: "active",
    totalSpent: 2200000,
    totalClasses: 12,
    registeredAt: "2026-04-05T00:00:00Z",
  },
];

// ===== Mock Escrow Transactions =====
export const mockEscrowTransactions: EscrowTransaction[] = [
  {
    id: "e1",
    studentName: "Đinh Văn Bình",
    tutorName: "Lê Văn Khoa",
    amount: 3600000,
    platformFee: 360000,
    netAmount: 3240000,
    status: "in_escrow",
    paidAt: "2026-05-01T10:00:00Z",
    courseTitle: "Lập trình Web Frontend",
    totalSessions: 12,
    completedSessions: 5,
  },
  {
    id: "e2",
    studentName: "Nguyễn Khánh Linh",
    tutorName: "Trần Minh Tuấn",
    amount: 2200000,
    platformFee: 220000,
    netAmount: 1980000,
    status: "in_escrow",
    paidAt: "2026-05-03T14:30:00Z",
    courseTitle: "IELTS 6.5 Target",
    totalSessions: 8,
    completedSessions: 2,
  },
];

// ===== Mock Payout Requests =====
export const mockPayoutRequests: PayoutRequest[] = [
  {
    id: "p1",
    tutorName: "Lê Văn Khoa",
    tutorAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=vankhoa",
    bankName: "Vietcombank",
    bankAccount: "0071000XXXXXXX",
    amount: 1350000,
    requestedAt: "2026-05-05T09:00:00Z",
    status: "pending",
  },
];

// ===== Mock Disputes =====
export const mockDisputes: Dispute[] = [
  {
    id: "d1",
    ticketCode: "DSP-001",
    createdBy: "student",
    creatorName: "Đinh Văn Bình",
    subjectName: "Trần Minh Tuấn",
    type: "tutor_absent",
    status: "new",
    outcome: null,
    escrowAmount: 2200000,
    completedSessions: 2,
    totalSessions: 8,
    createdAt: "2026-05-05T10:30:00Z",
    description:
      "Gia sư đã bỏ 2 buổi học liên tiếp mà không báo trước, không phản hồi tin nhắn.",
  },
  {
    id: "d2",
    ticketCode: "DSP-002",
    createdBy: "student",
    creatorName: "Nguyễn Khánh Linh",
    subjectName: "Võ Thị Hương",
    type: "quality_issue",
    status: "processing",
    outcome: null,
    escrowAmount: 1500000,
    completedSessions: 4,
    totalSessions: 6,
    createdAt: "2026-05-04T08:00:00Z",
    description: "Chất lượng giảng dạy không như mô tả, bài tập không được chấm.",
  },
];
